behaviors:
  PlatformerAgent2D:
    trainer_type: ppo
    max_steps: 2000000
    time_horizon: 128
    summary_freq: 20000
    checkpoint_interval: 50000
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 2.5e-4
      learning_rate_schedule: linear
      beta: 0.01
      epsilon: 0.2
      lambd: 0.97
      num_epoch: 4
    network_settings:
      normalize: true
      num_layers: 3
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        learning_rate: 3.0e-4
        encoding_size: 256
